package com.jtprince.coordinateoffset;

import com.jtprince.coordinateoffset.command.OffsetSetCommand;
import com.jtprince.coordinateoffset.provider.OffsetProvider;
import com.jtprince.coordinateoffset.provider.OffsetProviderContext;
import org.jspecify.annotations.NullMarked;
import org.jspecify.annotations.Nullable;

/**
 * Container for an offset which was generated for a specific context, and where the offset came from.
 *
 * @param offset The offset that was generated.
 * @param source Source of the offset. The offset may have come from an offset provider, or the offset may have been
 *               generated in response to an offset bypass or a command.
 * @param context Context in which the offset was generated.
 */
@NullMarked
public record OffsetData(
    Offset offset,
    Source source,
    OffsetProviderContext context
) {
    public sealed interface Source
        permits Source.PermissionBypass, Source.BedrockBypass, Source.Provider, Source.SetCommand {

        /** This offset is zero and was generated because the player has permission to bypass offsets. */
        record PermissionBypass() implements Source {}
        /** This offset is zero and was generated because the player is using Bedrock edition through Geyser. */
        record BedrockBypass() implements Source {}
        /** This offset was generated by a configured OffsetProvider class. */
        record Provider(OffsetProvider provider, boolean isOverride) implements Source {}
        /** This offset was explicitly set by a command. */
        record SetCommand(OffsetSetCommand command, @Nullable OffsetProvider affectedProvider) implements Source {}
    }
}
