package com.jtprince.coordinateoffset;

import com.jtprince.coordinateoffset.adapter.OffsetPlayer;
import com.jtprince.coordinateoffset.provider.OffsetProvider;
import com.jtprince.coordinateoffset.provider.OffsetProviderContext;
import org.jspecify.annotations.NullMarked;
import org.jspecify.annotations.Nullable;

/**
 * Container for an offset and where it came from.
 */
@NullMarked
public record CreatedOffset(
    Offset offset,
    Source source,
    OffsetPlayer player,
    String worldName,
    OffsetProviderContext.@Nullable ProvideReason reason
) {
    public sealed interface Source
        permits Source.PermissionBypass, Source.Provider, Source.SetCommand {

        /** This offset is zero and was generated because the player has permission to bypass offsets. */
        record PermissionBypass(CoordinateOffsetPermission perm) implements Source {}
        /** This offset was generated by a configured OffsetProvider class. */
        record Provider(OffsetProvider provider, boolean isOverride) implements Source {}
        /** This offset was explicitly set by a command. */
        record SetCommand(String sender) implements Source {}
    }

    public void log() {
        if (!CoordinateOffsetCore.get().getConfig().getVerbose()) return;

        StringBuilder s = new StringBuilder();
        s.append("Using ");
        s.append(offset);
        s.append(" from ");
        switch (source) {
            case Source.PermissionBypass p -> s.append("permission bypass");
            case Source.Provider p -> {
                s.append("provider \"").append(p.provider.name).append("\"");
                if (p.isOverride) {
                    s.append(" (config.yml override)");
                } else {
                    s.append(" (default provider)");
                }
            }
            case Source.SetCommand p -> s.append("command by ").append(p.sender);
        }
        s.append(" for player ");
        s.append(player.getName());
        s.append(" in world \"");
        s.append(worldName);
        s.append("\"");
        if (reason != null) {
            s.append(" (");
            switch (reason) {
                case JOIN -> s.append("player joined");
                case DEATH_RESPAWN -> s.append("player respawned");
                case WORLD_CHANGE -> s.append("player changed worlds");
                case TELEPORT -> s.append("player teleported");
                case COMMAND_REGENERATE -> s.append("regenerated by command");
                case PLUGIN_REGENERATE -> s.append("regenerated by external plugin");
            }
            s.append(")");
        }

        CoordinateOffsetCore.get().getLogger().info(s.toString());
    }
}
