package com.jtprince.coordinateoffset;

import com.jtprince.coordinateoffset.provider.OffsetProvider;
import com.jtprince.coordinateoffset.provider.OffsetProviderContext;
import org.jspecify.annotations.NullMarked;
import org.jspecify.annotations.Nullable;

/**
 * Container for an offset and where it came from.
 */
@NullMarked
public record CreatedOffset(
    Offset offset,
    Source source,
    OffsetProviderContext context
) {
    public sealed interface Source
        permits Source.PermissionBypass, Source.BedrockBypass, Source.Provider, Source.SetCommand {

        /** This offset is zero and was generated because the player has permission to bypass offsets. */
        record PermissionBypass(CoordinateOffsetPermission perm) implements Source {}
        /** This offset is zero and was generated because the player is using Bedrock edition through Geyser. */
        record BedrockBypass() implements Source {}
        /** This offset was generated by a configured OffsetProvider class. */
        record Provider(OffsetProvider provider, boolean isOverride) implements Source {}
        /** This offset was explicitly set by a command. */
        record SetCommand(String sender, @Nullable OffsetProvider affectedProvider) implements Source {}
    }

    public void log() {
        if (!CoordinateOffsetCore.get().getConfig().getVerbose()) return;

        StringBuilder s = new StringBuilder();
        s.append("Using ");
        s.append(offset);
        s.append(" from ");
        switch (source) {
            case Source.PermissionBypass ignored -> s.append("permission bypass");
            case Source.BedrockBypass ignored -> { return; /* Warning logged in OffsetCreator on Join only */ }
            case Source.Provider p -> {
                s.append("provider \"").append(p.provider.name).append("\"");
                if (p.isOverride) {
                    s.append(" (config.yml override)");
                } else {
                    s.append(" (default provider)");
                }
            }
            case Source.SetCommand p -> s.append("command by ").append(p.sender);
        }
        s.append(" for player ");
        s.append(context.player().getName());
        s.append(" in world \"");
        s.append(context.playerLocation().getWorld().getName());
        s.append("\"");
        s.append(switch (context.reason()) {
            case JOIN -> " (player joined)";
            case DEATH_RESPAWN -> " (player respawned)";
            case WORLD_CHANGE -> " (player changed worlds)";
            case TELEPORT -> " (player teleported)";
            case COMMAND_REGENERATE -> " (regenerated by command)";
            case COMMAND_SET -> ""; // already mentioned by source
            case PLUGIN_REGENERATE -> " (regenerated by external plugin)";
        });

        CoordinateOffsetCore.get().getLogger().info(s.toString());
    }
}
