[versions]
canvas = "1.21.8-R0.1-SNAPSHOT"
packetevents = "2.10.0-SNAPSHOT"
paper-api = "1.21.4-R0.1-SNAPSHOT"
paper-apiversion = "1.21.4" # plugin.yml apiVersion

[libraries]
adventure-api = { group = "net.kyori", name = "adventure-api", version = "4.25.0" }
bstats-bukkit = { group = "org.bstats", name = "bstats-bukkit", version = "3.1.0" }
configlib-core = { group = "de.exlll", name = "configlib-core", version = "4.6.3" }
configlib-paper = { group = "de.exlll", name = "configlib-paper", version = "4.6.3" }
geyser-api = { group = "org.geysermc.geyser", name = "api", version = "2.8.3-SNAPSHOT" }
jspecify = { group = "org.jspecify", name = "jspecify", version = "1.0.0" }
morepdt = { group = "com.jeff-media", name = "MorePersistentDataTypes", version = "2.4.0" }
packetevents-api = { group = "com.github.retrooper", name = "packetevents-api", version.ref = "packetevents" }
paper-api = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper-api" }
test-junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version = "5.11.4" }
test-junit-platform = { group = "org.junit.platform", name = "junit-platform-launcher" }

[plugins]
maven-publish = { id = "com.vanniktech.maven.publish", version = "0.34.0" }
paperweight-userdev = { id = "io.papermc.paperweight.userdev", version = "2.0.0-beta.19" }
shadow = { id = "com.gradleup.shadow", version = "9.2.2" }
