[versions]
packetevents = "2.10.0-SNAPSHOT"
paper-api = "1.21.5-R0.1-SNAPSHOT"
paper-apiversion = "1.21.5" # plugin.yml apiVersion

[libraries]
bstats-bukkit = { group = "org.bstats", name = "bstats-bukkit", version = "3.0.2" }
configlib-core = { group = "de.exlll", name = "configlib-core", version = "4.6.1" }
configlib-paper = { group = "de.exlll", name = "configlib-paper", version = "4.6.1" }
jetbrains-annotations = { group = "org.jetbrains", name = "annotations", version = "24.0.1" }
jspecify = { group = "org.jspecify", name = "jspecify", version = "1.0.0" }
morepdt = { group = "com.jeff-media", name = "MorePersistentDataTypes", version = "2.4.0" }
packetevents-api = { group = "com.github.retrooper", name = "packetevents-api", version.ref = "packetevents" }
paper-api = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper-api" }
test-junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version = "5.11.4" }
test-junit-platform = { group = "org.junit.platform", name = "junit-platform-launcher" }
