package com.jtprince.coordinateoffset.config;

import com.jtprince.coordinateoffset.CoordinateOffsetCore;
import de.exlll.configlib.Comment;
import de.exlll.configlib.Configuration;
import net.kyori.adventure.audience.Audience;
import net.kyori.adventure.text.minimessage.MiniMessage;
import net.kyori.adventure.text.minimessage.tag.resolver.TagResolver;
import org.jspecify.annotations.NullMarked;

@NullMarked
@Configuration
public class MessagesConfig {
    public Message prefix = new Message("<dark_aqua>[<#33A14F><hover:show_text:'<#33A14F>CoordinateOffset'>CO</hover></#33A14F>]</dark_aqua> ");

    @Configuration
    public static class Query {
        @Configuration public record C(Message offset, Message coordinates) {}
        public C self = new C(
            new Message("<gray>Your coordinate offset is: <dark_aqua>[x=<yellow><x></yellow>, z=<yellow><z></yellow>]"),
            new Message("<gray>Your real coordinates are: <light_purple>[x=<gold><x></gold>, y=<gold><y></gold>, z=<gold><z></gold>]")
        );
        public C other = new C(
            new Message("<gray><#18a9ff><target></#18a9ff>'s coordinate offset is: <dark_aqua>[x=<yellow><x></yellow>, z=<yellow><z></yellow>]"),
            new Message("<gray><#18a9ff><target></#18a9ff>'s real coordinates are: <light_purple>[x=<gold><x></gold>, y=<gold><y></gold>, z=<gold><z></gold>]")
        );
        public C selfNoOffset = new C(
            new Message("<gray>You have no coordinate offset applied."),
            new Message("<gray>The coordinates you see are the real coordinates of the world.")
        );

        @Configuration public static class Verbose {
            public Message zeroByPermission = new Message("<gray>No active offset due to permission bypass.");
            public Message zeroByBedrock = new Message("<gray>Coordinate offsets are not supported for Bedrock players.");
            public Message generatedByProviderDefault = new Message("<gray>This offset was generated by provider \"<green><provider></green>\", the default offset provider.");
            public Message generatedByProviderOverride = new Message("<gray>This offset was generated by provider \"<green><provider></green>\" as part of an offset provider override rule.");
            public Message generatedByCommand = new Message("<gray>This offset was set by a command sent by <#18a9ff><sender></#18a9ff>.");
            public Message generatedByPlugin = new Message("<gray>This offset was set by an external plugin.");
        }
        public Verbose verbose = new Verbose();
    }
    @Comment("")
    public Query query = new Query();

    @Configuration
    public static class Regenerate {
        public Message successSingle = new Message("<gray>Regenerated coordinate offset for <#18a9ff><target></#18a9ff>.");
        public Message successMultiple = new Message("<gray>Regenerated coordinate offsets for <#18a9ff><hover:show_text:'<#18a9ff><targets>'><count> players</hover></#18a9ff>.");
        public Message unchanged = new Message("<#CAD19F>Coordinate offset unchanged for <#18a9ff><target></#18a9ff>.");
        public Message unchangedPermission = new Message("<#CAD19F>Coordinate offset unchanged for <#18a9ff><target></#18a9ff> (player has permission to bypass offsets).");
        public Message unchangedBedrock = new Message("<#F09090>Coordinate offset unchanged for <#18a9ff><target></#18a9ff> (offsets are not supported for Bedrock players).");
    }
    @Comment("")
    public Regenerate regenerate = new Regenerate();

    @Configuration
    public static class Set {
        public Message successSingle = new Message("<gray>Set coordinate offset for <#18a9ff><target></#18a9ff> to <dark_aqua>[x=<yellow><x></yellow>, z=<yellow><z></yellow>]</dark_aqua>.");
        public Message successMultiple = new Message("<gray>Set coordinate offset for <#18a9ff><hover:show_text:'<#18a9ff><targets>'><count> players</hover></#18a9ff> to <dark_aqua>[x=<yellow><x></yellow>, z=<yellow><z></yellow>]</dark_aqua>.");
        public Message warningNotPersistentByPermission = new Message("<#CAD19F>Warning: offset for <#18a9ff><target></#18a9ff> is not persistent (player has offset bypass permission).");
        public Message warningNotPersistentByProvider = new Message("<#CAD19F>Warning: offset for <#18a9ff><target></#18a9ff> is not persistent (offset provider \"<provider>\" does not store offsets).");
        public Message invalidNotMultipleOf16 = new Message("<#F09090>Invalid offset: <component>=<red><value></red> is not a multiple of 16.");
        public Message unchanged = new Message("<#CAD19F>Coordinate offset unchanged for <#18a9ff><target></#18a9ff>.");
        public Message unchangedBedrock = new Message("<#F09090>Coordinate offset unchanged for <#18a9ff><target></#18a9ff> (offsets are not supported for Bedrock players).");
    }
    @Comment("")
    public Set set = new Set();

    @Configuration
    public static class Reload {
        public Message success = new Message("<green>CoordinateOffset configuration reloaded from file.");
        public Message fail = new Message("<red>Failed to reload CoordinateOffset configuration from file. Check the console for details.");
    }
    @Comment("")
    public Reload reload = new Reload();

    public record Message(String miniMessageStr) {
        public void send(Audience audience, TagResolver... resolvers) {
            if (miniMessageStr.isBlank()) return;

            audience.sendMessage(
                MiniMessage.miniMessage().deserialize(CoordinateOffsetCore.get().getMessages().prefix.miniMessageStr)
                    .append(MiniMessage.miniMessage().deserialize(miniMessageStr, resolvers)));
        }
    }

    public static class Serializer implements de.exlll.configlib.Serializer<Message, String> {
        @Override
        public String serialize(Message element) {
            return element.miniMessageStr;
        }

        @Override
        public Message deserialize(String element) {
            return new Message(element);
        }
    }
}
