name: Create Release

on:
  push:
    tags:
      - v*.*.*

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
      - name: Extract version from tag
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - name: Extract changelog
        # Find the section titled with the release version in CHANGELOG.md and extract it.
        run: |
          VERSION=$RELEASE_VERSION
          awk "/^# $VERSION\$/{flag=1; next} /^# /{flag=0} flag" CHANGELOG.md > release_changelog.md
          cat release_changelog.md
          if [ ! -s release_changelog.md ]; then
            echo "ERROR: CHANGELOG.md has no entry for $RELEASE_VERSION"
            exit 1
          fi
          echo "RELEASE_CHANGELOG<<EOF" >> $GITHUB_ENV
          cat release_changelog.md >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - name: Extract supported Minecraft versions
        # Extract the supported Minecraft versions from the extracted changelog.
        # Changelog must include a line right under the title between asterisks and with a colon, like:
        # *Supported Minecraft servers: Paper 1.21.4-1.21.10*
        run: |
          SUPPORTED_MC_LINE=$(echo "$RELEASE_CHANGELOG" | awk '/^\*/{print; exit}')
          MC_VERSIONS=$(echo "$SUPPORTED_MC_LINE" | sed -E 's/^[*][^:]+:[[:space:]]*(.*)[*]$/\1/')
          if [ -z "$MC_VERSIONS" ]; then
            echo "ERROR: Could not extract supported Minecraft versions from CHANGELOG.md"
            exit 1
          fi
          echo "SUPPORTED_MC_VERSIONS=$MC_VERSIONS" >> $GITHUB_ENV
          echo "Minecraft versions extracted: $SUPPORTED_MC_VERSIONS"
      - name: Build and test
        run: ./gradlew build
      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          name: ${{ env.RELEASE_VERSION }} (${{ env.SUPPORTED_MC_VERSIONS }})
          body: ${{ env.RELEASE_CHANGELOG }}
          draft: false
          prerelease: false
          make_latest: true
          files: paper/build/libs/*.jar
      - name: Create Hangar release
        # TODO: Re-enable configuration cache, https://github.com/HangarMC/hangar-publish-plugin/issues/40
        run: ./gradlew publishPluginPublicationToHangar --no-configuration-cache
        env:
          HANGAR_TOKEN: ${{ secrets.HANGAR_TOKEN }}
      - name: Create Modrinth release
        # TODO: Re-enable configuration cache, https://github.com/HangarMC/hangar-publish-plugin/issues/40
        run: ./gradlew modrinth --no-configuration-cache
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
